name: Build and upload

on:
  push:
    branches:
      - keymaster
  pull_request:
    types: [ opened, synchronize, reopened ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Configure Gradle cache
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --no-daemon --no-parallel --rerun-tasks --info --full-stacktrace build